logging:
  level:
    web: debug
    sql: debug
    org:
      springframework:
        test:
          context:
            transaction: debug
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:~/sites
    name: sa
    password:
    driver-class-name: org.h2.Driver
